### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ryan4794** [Im4wasp/W4SP-Stealer-Sourcecode#17]
Microsoft Windows [version 10.0.22621.2134]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\Bengal\Desktop\W4SP-Stealer-Sourcecode-main>C:\Users\Bengal\Desktop\W4SP-Stealer-Sourcecode-main\wasp-1.1.6.py
Exception in thread Thread-2 (getToken):
Traceback (most recent call last):
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
Exception in thread Thread-14 (getPassw):
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bengal\Desktop\W4SP-Stealer-Sourcecode-main\wasp-1.1.6.py", line 449, in getToken
Traceback (most recent call last):
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    for file in os.listdir(path):
    self.run()
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\Bengal\\AppData\\Roaming/Opera Software/Opera Stable/Local Storage/leveldb'
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
Exception in thread Thread-22 (getCookie):
Traceback (most recent call last):
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
['C:\\Users\\Bengal\\AppData\\Roaming/Opera Software/Opera GX Stable', 'opera.exe', '/Local Storage/leveldb', '/', '/Network', '/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
    self.run()
  File "C:\Users\Bengal\Desktop\W4SP-Stealer-Sourcecode-main\wasp-1.1.6.py", line 466, in getPassw
['C:\\Users\\Bengal\\AppData\\Roaming/Opera Software/Opera Stable', 'opera.exe', '/Local Storage/leveldb', '/', '/Network', '/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
['C:\\Users\\Bengal\\AppData\\Roaming/Opera Software/Opera Neon/User Data/Default', 'opera.exe', '/Local Storage/leveldb', '/', '/Network', '/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
['C:\\Users\\Bengal\\AppData\\Local/Google/Chrome/User Data', 'chrome.exe', '/Default/Local Storage/leveldb', '/Default', '/Default/Network', '/Default/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
    if os.stat(pathC).st_size == 0: return
    self._target(*self._args, **self._kwargs)
['C:\\Users\\Bengal\\AppData\\Local/Google/Chrome SxS/User Data', 'chrome.exe', '/Default/Local Storage/leveldb', '/Default', '/Default/Network', '/Default/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'C:\\Users\\Bengal\\AppData\\Roaming/Opera Software/Opera Stable//Login Data'
['C:\\Users\\Bengal\\AppData\\Local/BraveSoftware/Brave-Browser/User Data', 'brave.exe', '/Default/Local Storage/leveldb', '/Default', '/Default/Network', '/Default/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
  File "C:\Users\Bengal\Desktop\W4SP-Stealer-Sourcecode-main\wasp-1.1.6.py", line 507, in getCookie
['C:\\Users\\Bengal\\AppData\\Local/Yandex/YandexBrowser/User Data', 'yandex.exe', '/Default/Local Storage/leveldb', '/Default', '/Default/Network', '/HougaBouga/nkbihfbeogaeaoehlefnkodbefgpgknn']
['C:\\Users\\Bengal\\AppData\\Local/Microsoft/Edge/User Data', 'edge.exe', '/Default/Local Storage/leveldb', '/Default', '/Default/Network', '/Default/Local Extension Settings/nkbihfbeogaeaoehlefnkodbefgpgknn']
    if os.stat(pathC).st_size == 0: return
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'C:\\Users\\Bengal\\AppData\\Roaming/Opera Software/Opera Stable/Network/Cookies'
Exception in thread Thread-43 (ZipTelegram):
Traceback (most recent call last):
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Bengal\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bengal\Desktop\W4SP-Stealer-Sourcecode-main\wasp-1.1.6.py", line 629, in ZipTelegram
    if not os.pathC.exists(pathC): return
AttributeError: module 'os' has no attribute 'pathC'. Did you mean: 'path'?

if u lunch wasp-1.1.6

**Comment by Im4wasp** [comment]
yeah missclick idk
use the last version
